/// Flutter icons Apprise
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Apprise
///      fonts:
///       - asset: fonts/Apprise.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Apprise {
  Apprise._();

  static const _kFontFam = 'Apprise';
  static const String? _kFontPkg = null;

  static const IconData playstation = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pc = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xbox = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nintendo = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
